#ifndef _CONFIG_H_
#define _CONFIG_H_

#define ENTITIES_SAVE_PATH_BUFF_CAP 1024

#define ENTITY_DEFAULT_RADIUS 24
#define ENTITIES_MAX_CAP (1024*4)
#define ENTITY_TEXTURE_SCALE 2.0
#define ENTITY_SIZE_IN_PIXELS 16

#define MAC_ADDRESS_LENGTH 6

#define COMMAND_BUFF_CAP (1024*1)
#define AP_WIFI_WAVE_ALARM_TIME 1.0

#define COMMAND_PRERUN_FILENAME "prerun_command.momo"

#define ERROR_CONSOLE_ACTIVITY_VALUE 2.f

#endif // _CONFIG_H_
