#ifndef _CONFIG_H_
#define _CONFIG_H_

#define ENTITY_DEFAULT_RADIUS 24
#define ENTITIES_MAX_CAP (1024*4)
#define ENTITY_TEXTURE_SCALE 2.0
#define ENTITY_SIZE_IN_PIXELS 16
#define ENTITY_SAVE_VERSION 2

#define MAC_ADDRESS_LENGTH 6

#endif // _CONFIG_H_
